name: RL Scan

on:
  workflow_dispatch:

env:
  REPORT_PATH: "RLreport"

jobs:
  Build-And-Scan:
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE, so job can access it
      - name: Check out
        uses: actions/checkout@v4.1.1

      - name: Set Current Date Time
        run: |
          echo "DT_NOW=$(date +%Y%m%d-%H%M%S)" >> ${GITHUB_ENV}

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Build
        run: |
          mvn -B clean package

      - name: RL scan
        continue-on-error: true # Remove this line if you want the overall run to fail when the scan detects policy violations

        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}
          RLSECURE_PATH: "./RLSecure"
          PACKAGE_URL: "Apache/struts2-showcase@2.5.28"

        run: |
          # prepare to install
          python -m pip install --upgrade pip
          pip install rl-deploy
          rl-deploy --version
          mkdir -p ${RLSECURE_PATH} ./${REPORT_PATH}
          # install rl-secure
          rl-deploy install ${RLSECURE_PATH} \
            --encoded-key="${RLSECURE_ENCODED_LICENSE}" \
            --site-key="${RLSECURE_SITE_KEY}" \
            --no-tracking
          ${RLSECURE_PATH}/rl-secure init \
            -s ${RLSECURE_PATH}
          ${RLSECURE_PATH}/rl-secure \
            --version
          # scan the artifact
          ${RLSECURE_PATH}/rl-secure scan ./target/struts2-showcase.war \
            -s ${RLSECURE_PATH} \
            -p ${PACKAGE_URL} \
            --keep-reference \
            --no-tracking
          # make the report
          ${RLSECURE_PATH}/rl-secure report \
            -s ${RLSECURE_PATH} \
            -p ${PACKAGE_URL} \
            --format all \
            --output-path ./${REPORT_PATH}
          # report status and exit code
          ${RLSECURE_PATH}/rl-secure status \
            -s ${RLSECURE_PATH} \
            -p ${PACKAGE_URL} \
            --return-status

      - name: Archive Report
        if: success() || failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ReversingLabs-report-${{ env.DT_NOW }}
          path: ${{ env.REPORT_PATH }}

