name: RL Scan w/Docker image (self hosted)

on:
  workflow_dispatch:

env:
  # NODE_EXTRA_CA_CERTS: <your cert path> # add your cert if needed
  REPORT_PATH: "RLreport"

jobs:
  Build-And-Scan:
    runs-on: self-hosted

    steps:
      - name: Check out
        uses: actions/checkout@v4.1.1

      - name: Set Current Date Time
        run: |
          echo "DT_NOW=$(date +%Y%m%d-%H%M%S)" >> ${GITHUB_ENV}

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Build
        run: |
          mvn -B clean package

      - name: RL scan
        continue-on-error: true # Remove this line if you want the overall run to fail when the scan detects policy violations

        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}

        run: |
          mkdir $(pwd)/${REPORT_PATH}
          docker run --pull always --rm \
            -u $(id -u):$(id -g) \
            -v "$(pwd)/target:/packages:ro" \
            -v "$(pwd)/${REPORT_PATH}:/report" \
            -e RLSECURE_ENCODED_LICENSE="${RLSECURE_ENCODED_LICENSE}" \
            -e RLSECURE_SITE_KEY="${RLSECURE_SITE_KEY}" \
            reversinglabs/rl-scanner \
              rl-scan \
                --package-path=/packages/struts2-showcase.war \
                --report-path=/report \
                --report-format=all

      - name: Archive Report
        if: success() || failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ReversingLabs-report-${{ env.DT_NOW }}
          path: ${{ env.REPORT_PATH }}
